# Generated by Django 4.2.7 on 2023-11-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('temporadas', models.IntegerField()),
                ('Capitulos', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
