# Generated by Django 4.2.7 on 2023-11-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(default='AppPro/img/posterdefault.jpg', upload_to='AppPro/img'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.CharField(default='Sin sinopsis disponible', max_length=1000),
        ),
        migrations.AddField(
            model_name='serie',
            name='poster',
            field=models.ImageField(default='AppPro/img/posterdefault.jpg', upload_to='AppPro/img'),
        ),
        migrations.AddField(
            model_name='serie',
            name='sinopsis',
            field=models.CharField(default='Sin sinopsis disponible', max_length=1000),
        ),
        migrations.AlterField(
            model_name='serie',
            name='Capitulos',
            field=models.IntegerField(max_length=600),
        ),
        migrations.AlterField(
            model_name='serie',
            name='temporadas',
            field=models.IntegerField(max_length=100),
        ),
    ]
