# Generated by Django 4.2.7 on 2023-11-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPro', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='AppPro/img/avatar.png', null=True, upload_to='fotos_perfil/'),
        ),
    ]
