# Generated by Django 4.2.7 on 2023-11-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPro', '0004_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ig',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
