# Generated by Django 4.2.7 on 2023-11-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPro', '0005_perfil_ig_perfil_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='ejemplo@ejemplo.com', max_length=254),
        ),
    ]
