# Generated by Django 4.2.7 on 2023-11-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPro', '0006_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AddField(
            model_name='serie',
            name='anio',
            field=models.IntegerField(default='0000'),
        ),
    ]
