# Generated by Django 4.2.7 on 2023-11-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPro', '0007_pelicula_anio_serie_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
